FROM kexin.tencentcloudcr.com/basic/node:master as builder

COPY . .
RUN yarn
RUN yarn web:build

FROM nginx:1.21-alpine as nginx
ADD nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /node/packages/web/dist /app
